export const images = {
  logo: require("../assets/images/logo.png"),
  googleIcon: require("../assets/images/google-icon.svg"),
  appleIcon: require("../assets/images/apple-icon.svg"),
  loginRightSidebar: require("../assets/images/login-right-sidebar.png"),
  testUser: require("../assets/images/test-user.svg"),
  warningModalImage: require("../assets/images/success-modal.svg"),
  successModalImage: require("../assets/images/success-modal2.svg"),
  checkIncon: require("../assets/images/check.svg"),
  refreshIcon: require("../assets/images/refreshIcon.svg"),
  deleteIcon: require("../assets/images/deleteIcon.svg"),
  pencil_icon: require("../assets/images/pencil_icon.svg"),
  pin_icon: require("../assets/images/pin.svg"),
  file_icon: require("../assets/images/fileIcon.svg"),
};
